services:
  php:
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      APP_SECRET: EDITME
      DATABASE_URL: "mysql://root@mysql/sylius_%kernel.environment%"
      MAILER_URL: smtp://mailhog:1025
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: >-
        client_host=host.docker.internal
        client_port=9003
        log=/dev/stdout
      PHP_IDE_CONFIG: serverName=sylius
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/srv/sylius:rw,cached
      - public-media:/srv/sylius/public/media:rw
    networks:
      - php
      - mysql
  
  nginx:
    volumes:
      - ./public:/srv/sylius/public:ro
      - public-media:/srv/sylius/public/media:ro,nocopy
    ports:
      - "80:80"
    networks:
      - php
  
  nodejs:
    environment:
      GULP_ENV: dev
      PHP_HOST: php
      PHP_PORT: 9000
    working_dir: /srv/sylius
    entrypoint: [ "/bin/sh","-c" ]
    command:
      - |
        yarn install
        yarn build
    volumes:
      - .:/srv/sylius:rw,cached
      - ./public:/srv/sylius/public:rw,delegated
    ports:
      - "35729:35729"
    networks:
      - php
    profiles:
      - js
  
  mysql:
    healthcheck:
      test: "/usr/bin/mysql --user=root --execute \"SHOW databases;\""
      timeout: 5s
      interval: 5s
      retries: 5
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql-data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    networks:
      - mysql
