services:
  nginx:
    image: bitbag/sylius-nginx:latest
  
  php:
    image: bitbag/sylius-php:8.1-xdebug-alpine
    environment:
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    cap_add:
      - SYS_NICE

  nodejs:
    image: "node:${NODE_VERSION:-16}-alpine"

volumes:
  mysql-data:
  public-media:
    
networks:
  php:
  mysql:
